ALTER TABLE events
ADD COLUMN IF NOT EXISTS start_latitude DECIMAL(10,8),
ADD COLUMN IF NOT EXISTS start_longitude DECIMAL(11,8),
ADD COLUMN IF NOT EXISTS finish_latitude DECIMAL(10,8),
ADD COLUMN IF NOT EXISTS finish_longitude DECIMAL(11,8),
ADD COLUMN IF NOT EXISTS race_status VARCHAR(20) DEFAULT 'CREATED',
ADD COLUMN IF NOT EXISTS race_started_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS race_paused_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS race_resumed_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS race_finished_at TIMESTAMP;

ALTER TABLE events
ADD CONSTRAINT chk_race_status
CHECK (race_status IN ('CREATED', 'READY', 'STARTED', 'PAUSED', 'FINISHED', 'CANCELLED'));